name: Python Application CI Pipeline

on:
  push:
      branches:
        - main
        - dev

  workflow_dispatch:
env:
  APP_NAME : my-python-app
  ENVIRONMENT : production

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: checking out
        uses: actions/checkout@v6

      - name: Displaying information
        run: |
          hostname
          cat /etc/os-release
          python --version
          ls -ltrh
        
      - name: Run application
        run: python app.py

      - name: Checking Status
        if: ${{ success() }}
        run: echo "Job success"

      - name: checking status
        if: ${{ failure() }}
        run: echo "Job failed"

  build:

    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Building stage
        run: echo $APP_NAME

      - name: Hostname 
        run: hostname

      - name: Result
        run: echo "Build completed successfully"


  deploy:
  
    runs-on: ubuntu-latest
    needs: build

    if: ${{ github.ref == 'refs/heads/main' }}
    steps:

      - name: Deploying app
        run: echo "Deploying $APP_NAME to $ENVIRONMENT"

      - name: Final result
        run: echo "Deployment completed successfully"
  
  
  
  


  
      


