name: Drill1

on: 
  push:
    branches: main

  workflow_dispatch: 

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git code
        uses: actions/checkout@v7

      - name: listing files
        run: ls -ltrh
